version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    command: daphne app.asgi:application
    depends_on:
      - db

  react:
    build: ./frontend/cat-app
    ports:
      - "3000:3000"
    command: npm start
  db:
    image: postgres:latest