version: '3.3'

services:
  db:
    image: postgres
    env_file: app/.env
    networks:
      - backend
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    ports:
      - "5433:5432"

  app:
    build:
      context: app
      dockerfile: Dockerfile
    networks:
      - backend

  react:
    build: frontend/cat-app
    ports:
      - "3000:3000"
    command: npm start

networks:
  backend: