version: '3.3'

services:
  app:
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - backend

  react:
    build: frontend/cat-app
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend: